### ISSUE TITLE
Super Block Grid layer always shows 64x64 grid

### ISSUE THREAD

**Issue by damian101** [pengbins/aomanalyzer.io#2]
I assume this is an upstream issue, but somehow the "Super Block Grid" layer always shows a 64x64 grid, regardless of the actual superblock sizes.

**Comment by pengbins** [comment]
https://github.com/xiph/aomanalyzer/blob/master/src/components/analyzerTools.ts#L446

**Comment by pengbins** [comment]
Should be fixed on the latest version.

**Comment by damian101** [comment]
Fixed indeed :)
