### ISSUE TITLE
How is reference list computed in "Histogram Tab"

### ISSUE THREAD

**Issue by zwayn** [pengbins/aomanalyzer.io#3]
Hello, I was wondering how the list of reference frames with frame number is computed ?

**Comment by pengbins** [comment]
Just extracted from aom decoder.

**Comment by zwayn** [comment]
modified version of inspection ?

**Comment by pengbins** [comment]
Yes

**Comment by zwayn** [comment]
is it possible to have access to it ?

**Comment by pengbins** [comment]
https://github.com/pengbins/aomanalyzer.io/blob/master/dist/inspect.js 
https://github.com/pengbins/aomanalyzer.io/blob/master/dist/inspect.wasm

**Comment by git-bauerseb** [comment]
Hi,
really cool project!

I have a question about the information displayed in *Reference Frame* under the *Block Info* tab. I see a number displayed there — does this represent the actual index in the video sequence that the motion vectors refer to?

If so, I have a couple of questions:

- do you trace the motion vectors back until encountering a DCT/Intra-predicted block? If so, how do you handle ambiguity? For example, if a motion vector is (2.5, 2.5), it lies precisely between four blocks; how do you determine the correct one?

- What order of reference frame types do you use? For every type (LAST_FRAME, LAST2_FRAME, LAST3_FRAME, GOLDEN_FRAME, BWDREF_FRAME, ALTREF2_FRAME, ALTREF_FRAME) how do you determine how much into the future/past you need to go?

I tried analyzing the analyzer.bundle.js file by undoing the minification and formatting it, but I couldn’t figure out how it works.
